// Generated by https://quicktype.io

import { Platillo } from "src/app/platillos/models/platillo.model";

export interface Ordenes {
  total: number;
  orden: Orden[];
}

export interface Orden {
  _id?:          string;
  platos?:       Plato[];
  estado?:       string;
  fecha_pedido?: string;
  anotaciones?: string;
}

export interface Plato {
  plato:        Platillo;
  cantidad?:  number;
  adiciones?: string[];
}


export interface OrdenV2 {
  platos?:       PlatoV2[];
  estado?:       string;
  fecha_pedido?: string;
  anotaciones?: string;
}

export interface PlatoV2 {
  plato:        string;
  cantidad?:  number;
  adiciones?: string[];
}
