// Generated by https://quicktype.io

import { Platillo } from "src/app/platillos/models/platillo.model";

export interface Ordenes {
  total:  number;
  platos: Orden[];
}

export interface Orden {
  _id?:          string;
  platos:       Platillo[];
  adiciones?:    any[];
  estado?:       string;
  fecha_pedido?: string;
  descripcion?:          string;
}

